import { TransactionType } from '../enums';

export const storeTr = {
  data: {
    transactions: [
      {
        id: '1',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory2',
        amount: 500,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory1',
        amount: 50,
        description: 'string',
      },
      {
        id: '3',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory7',
        amount: 520,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory2',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory3',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory6',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory2',
        amount: 38,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory4',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Expenses,
        account: '689',
        category: 'defaultCategory1',
        amount: 40,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Income,
        account: '689',
        category: 'defaultCategory9',
        amount: 4050,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Income,
        account: '689',
        category: 'defaultCategory9',
        amount: 550,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Income,
        account: '689',
        category: 'defaultCategory9',
        amount: 35,
        description: 'string',
      },
      {
        id: '4',
        date: Date.now(),
        type: TransactionType.Income,
        account: '689',
        category: 'defaultCategory9',
        amount: 12,
        description: 'string',
      },
    ],
  },
};
