export const storeTr = {
  data: {
    transactions: [
      {
        id: '1',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '2',
        amount: 500,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '1',
        amount: 50,
        description: 'string',
      },
      {
        id: '3',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '7',
        amount: 520,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '2',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '3',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '6',
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: '2',
        amount: 38,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: 4,
        amount: 80,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'expenses',
        account: 689,
        category: 1,
        amount: 40,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'income',
        account: 689,
        category: null,
        amount: 4050,
        description: 'string',
      },
      {
        id: '4',
        date: Date,
        type: 'income',
        account: 689,
        category: null,
        amount: 50,
        description: 'string',
      },
    ],
  },
};
